[project]
name = "gan-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gensim>=4.3.3",
    "keras>=3.11.3",
    "matplotlib>=3.10.6",
    "pandas>=2.3.2",
    "tensorflow>=2.18.1",
]
